import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
] 

[env]
TERM = "xterm-256color"

[font]
normal.family = "Hack Nerd Font"
size = 20

[window]
blur = true
decorations = "Full"
decorations_theme_variant = "Dark"
opacity = 0.8
option_as_alt = "OnlyRight"
padding = { x = 0, y = 0 }
